// This file is auto-generated by @hey-api/openapi-ts
import {
  type Client,
  type Options as ClientOptions,
  type TDataShape,
  formDataBodySerializer,
} from "@hey-api/client-fetch";

import { client as _heyApiClient } from "./client.gen";
import type {
  AuthControllerLoginByPhoneData,
  AuthControllerLoginByPhoneResponse,
  AuthControllerLoginData,
  AuthControllerLoginResponse,
  AuthControllerRefreshTokensData,
  AuthControllerRefreshTokensResponse,
  AuthControllerRegisterData,
  AuthControllerRegisterResponse,
  CompanyControllerDeleteData,
  CompanyControllerDeleteResponse,
  CompanyControllerGetByIdData,
  CompanyControllerGetByIdResponse,
  CompanyControllerListData,
  CompanyControllerListResponse,
  CompanyControllerUpdateData,
  CompanyControllerUpdateResponse,
  FilesControllerGetFileData,
  FilesControllerUploadFileData,
  JobseekerControllerDeleteData,
  JobseekerControllerDeleteResponse,
  JobseekerControllerGetByIdData,
  JobseekerControllerGetByIdResponse,
  JobseekerControllerListData,
  JobseekerControllerListResponse,
  JobseekerControllerUpdateData,
  JobseekerControllerUpdateResponse,
  JobseekerControllerUploadPhotoData,
  JobseekerControllerUploadPhotoResponse,
  JobseekerControllerUploadVideoData,
  JobseekerControllerUploadVideoResponse,
  RegistrationControllerCompleteRegistrationData,
  RegistrationControllerCompleteRegistrationResponse,
  RegistrationControllerGetRegistrationStatusData,
  RegistrationControllerGetRegistrationStatusResponse,
  RegistrationControllerProcessStep2Data,
  RegistrationControllerProcessStep3Data,
  RegistrationControllerProcessStep5Data,
  RegistrationControllerSendSmsCodeData,
  RegistrationControllerStartRegistrationData,
  RegistrationControllerStartRegistrationError,
  RegistrationControllerStartRegistrationResponse,
  RegistrationControllerVerifySmsCodeData,
  ResumeControllerCreateData,
  ResumeControllerCreateResponse,
  ResumeControllerDeleteData,
  ResumeControllerDeleteResponse,
  ResumeControllerListData,
  ResumeControllerListResponse,
  ResumeControllerUpdateData,
  ResumeControllerUpdateResponse,
  SubscriptionAdminControllerCreateCompanySubscriptionData,
  SubscriptionAdminControllerCreateCompanySubscriptionResponse,
  SubscriptionAdminControllerDeleteSubscriptionData,
  SubscriptionAdminControllerDeleteSubscriptionResponse,
  SubscriptionAdminControllerGetAllSubscriptionsData,
  SubscriptionAdminControllerGetAllSubscriptionsResponse,
  SubscriptionAdminControllerGetSubscriptionByIdData,
  SubscriptionAdminControllerGetSubscriptionByIdResponse,
  SubscriptionAdminControllerUpdateSubscriptionData,
  SubscriptionAdminControllerUpdateSubscriptionResponse,
  SubscriptionControllerCreateData,
  SubscriptionControllerCreateResponse,
  SubscriptionControllerGetCurrentData,
  UserControllerListData,
  UserControllerListResponse,
  UserControllerMeData,
  UserControllerMeResponse,
  VacancyControllerCreateByCompanyIdData,
  VacancyControllerCreateByCompanyIdResponse,
  VacancyControllerCreateData,
  VacancyControllerCreateResponse,
  VacancyControllerDeleteData,
  VacancyControllerDeleteMultipleData,
  VacancyControllerDeleteMultipleResponse,
  VacancyControllerGetByCompanyIdData,
  VacancyControllerGetByCompanyIdResponse,
  VacancyControllerGetByIdData,
  VacancyControllerGetByIdResponse,
  VacancyControllerListData,
  VacancyControllerListResponse,
  VacancyControllerUpdateByCompanyIdData,
  VacancyControllerUpdateByCompanyIdResponse,
  VacancyControllerUpdateData,
  VacancyControllerUpdateResponse,
} from "./types.gen";
import {
  zAuthControllerLoginByPhoneResponse,
  zAuthControllerLoginResponse,
  zAuthControllerRefreshTokensResponse,
  zAuthControllerRegisterResponse,
  zCompanyControllerDeleteResponse,
  zCompanyControllerGetByIdResponse,
  zCompanyControllerListResponse,
  zCompanyControllerUpdateResponse,
  zJobseekerControllerDeleteResponse,
  zJobseekerControllerGetByIdResponse,
  zJobseekerControllerListResponse,
  zJobseekerControllerUpdateResponse,
  zJobseekerControllerUploadPhotoResponse,
  zJobseekerControllerUploadVideoResponse,
  zRegistrationControllerCompleteRegistrationResponse,
  zRegistrationControllerGetRegistrationStatusResponse,
  zRegistrationControllerStartRegistrationResponse,
  zResumeControllerCreateResponse,
  zResumeControllerDeleteResponse,
  zResumeControllerListResponse,
  zResumeControllerUpdateResponse,
  zSubscriptionAdminControllerCreateCompanySubscriptionResponse,
  zSubscriptionAdminControllerDeleteSubscriptionResponse,
  zSubscriptionAdminControllerGetAllSubscriptionsResponse,
  zSubscriptionAdminControllerGetSubscriptionByIdResponse,
  zSubscriptionAdminControllerUpdateSubscriptionResponse,
  zSubscriptionControllerCreateResponse,
  zUserControllerListResponse,
  zUserControllerMeResponse,
  zVacancyControllerCreateByCompanyIdResponse,
  zVacancyControllerCreateResponse,
  zVacancyControllerDeleteMultipleResponse,
  zVacancyControllerGetByCompanyIdResponse,
  zVacancyControllerGetByIdResponse,
  zVacancyControllerListResponse,
  zVacancyControllerUpdateByCompanyIdResponse,
  zVacancyControllerUpdateResponse,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Регистрация нового пользователя (пример регистрации соискателя) ✍️
 */
export const authControllerRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRegisterData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerRegisterResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zAuthControllerRegisterResponse.parseAsync(data);
    },
    url: "/api/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Авторизация пользователя 🔐
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<AuthControllerLoginResponse, unknown, ThrowOnError>(
    {
      responseValidator: async (data) => {
        return await zAuthControllerLoginResponse.parseAsync(data);
      },
      url: "/api/auth/login",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    },
  );
};

/**
 * Вход в систему по номеру телефона 📲
 */
export const authControllerLoginByPhone = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginByPhoneData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerLoginByPhoneResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zAuthControllerLoginByPhoneResponse.parseAsync(data);
    },
    url: "/api/auth/login-by-phone",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Обновление токенов доступа 🔏
 * Обновляет access и refresh токены, используя текущий refresh токен
 */
export const authControllerRefreshTokens = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRefreshTokensData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerRefreshTokensResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zAuthControllerRefreshTokensResponse.parseAsync(data);
    },
    url: "/api/auth/refresh",
    ...options,
  });
};

/**
 * Начать процесс регистрации (шаг 1)
 */
export const registrationControllerStartRegistration = <ThrowOnError extends boolean = false>(
  options: Options<RegistrationControllerStartRegistrationData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    RegistrationControllerStartRegistrationResponse,
    RegistrationControllerStartRegistrationError,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zRegistrationControllerStartRegistrationResponse.parseAsync(data);
    },
    url: "/api/registration/start",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Обработать второй шаг регистрации
 */
export const registrationControllerProcessStep2 = <ThrowOnError extends boolean = false>(
  options: Options<RegistrationControllerProcessStep2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    url: "/api/registration/full-name",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Обработать третий шаг регистрации
 */
export const registrationControllerProcessStep3 = <ThrowOnError extends boolean = false>(
  options: Options<RegistrationControllerProcessStep3Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    url: "/api/registration/phone",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Отправить SMS с кодом подтверждения
 */
export const registrationControllerSendSmsCode = <ThrowOnError extends boolean = false>(
  options: Options<RegistrationControllerSendSmsCodeData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    url: "/api/registration/send-sms",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Проверить код подтверждения (шаг 4)
 */
export const registrationControllerVerifySmsCode = <ThrowOnError extends boolean = false>(
  options: Options<RegistrationControllerVerifySmsCodeData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    url: "/api/registration/verify-sms",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Обработать пятый шаг регистрации
 */
export const registrationControllerProcessStep5 = <ThrowOnError extends boolean = false>(
  options: Options<RegistrationControllerProcessStep5Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    url: "/api/registration/send-data",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Завершить регистрацию и получить токены
 */
export const registrationControllerCompleteRegistration = <ThrowOnError extends boolean = false>(
  options: Options<RegistrationControllerCompleteRegistrationData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    RegistrationControllerCompleteRegistrationResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zRegistrationControllerCompleteRegistrationResponse.parseAsync(data);
    },
    url: "/api/registration/complete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Получить текущий шаг регистрации
 */
export const registrationControllerGetRegistrationStatus = <ThrowOnError extends boolean = false>(
  options: Options<RegistrationControllerGetRegistrationStatusData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    RegistrationControllerGetRegistrationStatusResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zRegistrationControllerGetRegistrationStatusResponse.parseAsync(data);
    },
    url: "/api/registration/status/{sessionId}",
    ...options,
  });
};

/**
 * Получение информации о текущем пользователе 👤
 * Возвращает информацию об аутентифицированном пользователе.
 */
export const userControllerMe = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerMeData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<UserControllerMeResponse, unknown, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zUserControllerMeResponse.parseAsync(data);
    },
    url: "/api/user/me",
    ...options,
  });
};

/**
 * Получение всех вакансий и компаний 🏢👥
 * Возвращает список всех вакансий и компаний.
 */
export const userControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<UserControllerListResponse, unknown, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zUserControllerListResponse.parseAsync(data);
    },
    url: "/api/user/list",
    ...options,
  });
};

/**
 * Получить список всех вакансий 📖
 */
export const vacancyControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<VacancyControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    VacancyControllerListResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zVacancyControllerListResponse.parseAsync(data);
    },
    url: "/api/vacancy/list",
    ...options,
  });
};

/**
 * Получить вакансию по ID 🆔
 */
export const vacancyControllerGetById = <ThrowOnError extends boolean = false>(
  options: Options<VacancyControllerGetByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    VacancyControllerGetByIdResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zVacancyControllerGetByIdResponse.parseAsync(data);
    },
    url: "/api/vacancy/{id}",
    ...options,
  });
};

/**
 * Создать новую вакансию 📝
 */
export const vacancyControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<VacancyControllerCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    VacancyControllerCreateResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zVacancyControllerCreateResponse.parseAsync(data);
    },
    url: "/api/vacancy/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Обновить существующую вакансию 🔄
 */
export const vacancyControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<VacancyControllerUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    VacancyControllerUpdateResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zVacancyControllerUpdateResponse.parseAsync(data);
    },
    url: "/api/vacancy/update/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Удалить существующую вакансию 🗑️
 */
export const vacancyControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<VacancyControllerDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/vacancy/delete/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Удалить вакансии компании 🗑️
 */
export const vacancyControllerDeleteMultiple = <ThrowOnError extends boolean = false>(
  options: Options<VacancyControllerDeleteMultipleData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    VacancyControllerDeleteMultipleResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zVacancyControllerDeleteMultipleResponse.parseAsync(data);
    },
    url: "/api/vacancy/by-company/{companyId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Получить список вакансий по ID компании 🏢
 */
export const vacancyControllerGetByCompanyId = <ThrowOnError extends boolean = false>(
  options: Options<VacancyControllerGetByCompanyIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    VacancyControllerGetByCompanyIdResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zVacancyControllerGetByCompanyIdResponse.parseAsync(data);
    },
    url: "/api/vacancy/by-company/{companyId}",
    ...options,
  });
};

/**
 * Создать новую вакансию для компании 📝
 */
export const vacancyControllerCreateByCompanyId = <ThrowOnError extends boolean = false>(
  options: Options<VacancyControllerCreateByCompanyIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    VacancyControllerCreateByCompanyIdResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zVacancyControllerCreateByCompanyIdResponse.parseAsync(data);
    },
    url: "/api/vacancy/by-company/{companyId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Обновить существующую вакансию компании 🔄
 */
export const vacancyControllerUpdateByCompanyId = <ThrowOnError extends boolean = false>(
  options: Options<VacancyControllerUpdateByCompanyIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    VacancyControllerUpdateByCompanyIdResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zVacancyControllerUpdateByCompanyIdResponse.parseAsync(data);
    },
    url: "/api/vacancy/by-company/{companyId}/vacancy/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Получение списка всех компаний 📋
 */
export const companyControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<CompanyControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    CompanyControllerListResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zCompanyControllerListResponse.parseAsync(data);
    },
    url: "/api/companies/list",
    ...options,
  });
};

/**
 * Получение компании по ID 🔍
 */
export const companyControllerGetById = <ThrowOnError extends boolean = false>(
  options: Options<CompanyControllerGetByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    CompanyControllerGetByIdResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zCompanyControllerGetByIdResponse.parseAsync(data);
    },
    url: "/api/companies/{id}",
    ...options,
  });
};

/**
 * Обновление информации о вакансии 🔄
 */
export const companyControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CompanyControllerUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    CompanyControllerUpdateResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zCompanyControllerUpdateResponse.parseAsync(data);
    },
    url: "/api/companies/update/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Удаление существующей компании 🗑️
 */
export const companyControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<CompanyControllerDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    CompanyControllerDeleteResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zCompanyControllerDeleteResponse.parseAsync(data);
    },
    url: "/api/companies/delete/{id}",
    ...options,
  });
};

/**
 * Получение соискателя по ID 👤
 */
export const jobseekerControllerGetById = <ThrowOnError extends boolean = false>(
  options: Options<JobseekerControllerGetByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    JobseekerControllerGetByIdResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zJobseekerControllerGetByIdResponse.parseAsync(data);
    },
    url: "/api/jobseeker/{id}",
    ...options,
  });
};

/**
 * Получение списка всех соискателей 📋
 */
export const jobseekerControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<JobseekerControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    JobseekerControllerListResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zJobseekerControllerListResponse.parseAsync(data);
    },
    url: "/api/jobseeker/list",
    ...options,
  });
};

/**
 * Обновление информации о соискателе 🔄
 */
export const jobseekerControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<JobseekerControllerUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    JobseekerControllerUpdateResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zJobseekerControllerUpdateResponse.parseAsync(data);
    },
    url: "/api/jobseeker/update/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Удаление существующего соискателя 🗑️
 */
export const jobseekerControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<JobseekerControllerDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    JobseekerControllerDeleteResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zJobseekerControllerDeleteResponse.parseAsync(data);
    },
    url: "/api/jobseeker/delete/{id}",
    ...options,
  });
};

/**
 * Загрузка фотографии соискателя 📷
 */
export const jobseekerControllerUploadPhoto = <ThrowOnError extends boolean = false>(
  options: Options<JobseekerControllerUploadPhotoData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    JobseekerControllerUploadPhotoResponse,
    unknown,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zJobseekerControllerUploadPhotoResponse.parseAsync(data);
    },
    url: "/api/jobseeker/{id}/upload-photo",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });
};

/**
 * Загрузка видео соискателя 🎥
 */
export const jobseekerControllerUploadVideo = <ThrowOnError extends boolean = false>(
  options: Options<JobseekerControllerUploadVideoData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    JobseekerControllerUploadVideoResponse,
    unknown,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zJobseekerControllerUploadVideoResponse.parseAsync(data);
    },
    url: "/api/jobseeker/{id}/upload-video",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });
};

/**
 * Получить список всех резюме 📄
 * Возвращает список резюме с возможностью фильтрации по различным параметрам
 */
export const resumeControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<ResumeControllerListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ResumeControllerListResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zResumeControllerListResponse.parseAsync(data);
    },
    url: "/api/resume/list",
    ...options,
  });
};

/**
 * Создать новое резюме 📝
 */
export const resumeControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<ResumeControllerCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ResumeControllerCreateResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zResumeControllerCreateResponse.parseAsync(data);
    },
    url: "/api/resume/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Обновить существующее резюме 🔄
 */
export const resumeControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ResumeControllerUpdateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    ResumeControllerUpdateResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zResumeControllerUpdateResponse.parseAsync(data);
    },
    url: "/api/resume/update/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Удалить существующее резюме 🗑️
 */
export const resumeControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<ResumeControllerDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    ResumeControllerDeleteResponse,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    responseValidator: async (data) => {
      return await zResumeControllerDeleteResponse.parseAsync(data);
    },
    url: "/api/resume/delete/{id}",
    ...options,
  });
};

/**
 * Создание подписки для компании
 * Создаёт новую подписку для работодателя
 */
export const subscriptionControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<SubscriptionControllerCreateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    SubscriptionControllerCreateResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zSubscriptionControllerCreateResponse.parseAsync(data);
    },
    url: "/api/subscriptions/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Получить текущую подписку
 * Возвращает активную подписку текущего работодателя
 */
export const subscriptionControllerGetCurrent = <ThrowOnError extends boolean = false>(
  options?: Options<SubscriptionControllerGetCurrentData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: "/api/subscriptions/current",
    ...options,
  });
};

/**
 * Создание подписки для компании
 * Создает новую подписку для указанной компании
 */
export const subscriptionAdminControllerCreateCompanySubscription = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SubscriptionAdminControllerCreateCompanySubscriptionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    SubscriptionAdminControllerCreateCompanySubscriptionResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zSubscriptionAdminControllerCreateCompanySubscriptionResponse.parseAsync(data);
    },
    url: "/api/adm/subscriptions/company",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Получение всех подписок
 * Возвращает список всех подписок компаний
 */
export const subscriptionAdminControllerGetAllSubscriptions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SubscriptionAdminControllerGetAllSubscriptionsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    SubscriptionAdminControllerGetAllSubscriptionsResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zSubscriptionAdminControllerGetAllSubscriptionsResponse.parseAsync(data);
    },
    url: "/api/adm/subscriptions/company/all",
    ...options,
  });
};

/**
 * Удаление подписки
 * Удаляет подписку по указанному ID
 */
export const subscriptionAdminControllerDeleteSubscription = <ThrowOnError extends boolean = false>(
  options: Options<SubscriptionAdminControllerDeleteSubscriptionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    SubscriptionAdminControllerDeleteSubscriptionResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zSubscriptionAdminControllerDeleteSubscriptionResponse.parseAsync(data);
    },
    url: "/api/adm/subscriptions/company/{id}",
    ...options,
  });
};

/**
 * Получение подписки по ID
 * Возвращает подписку по указанному ID
 */
export const subscriptionAdminControllerGetSubscriptionById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SubscriptionAdminControllerGetSubscriptionByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    SubscriptionAdminControllerGetSubscriptionByIdResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zSubscriptionAdminControllerGetSubscriptionByIdResponse.parseAsync(data);
    },
    url: "/api/adm/subscriptions/company/{id}",
    ...options,
  });
};

/**
 * Обновление подписки
 * Обновляет существующую подписку по указанному ID
 */
export const subscriptionAdminControllerUpdateSubscription = <ThrowOnError extends boolean = false>(
  options: Options<SubscriptionAdminControllerUpdateSubscriptionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    SubscriptionAdminControllerUpdateSubscriptionResponse,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) => {
      return await zSubscriptionAdminControllerUpdateSubscriptionResponse.parseAsync(data);
    },
    url: "/api/adm/subscriptions/company/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Загрузка файла
 * Загружает файл и связывает его с указанной сущностью
 */
export const filesControllerUploadFile = <ThrowOnError extends boolean = false>(
  options: Options<FilesControllerUploadFileData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: "/api/files/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });
};

/**
 * Получение файла по ID
 * Возвращает файл по его ID
 */
export const filesControllerGetFile = <ThrowOnError extends boolean = false>(
  options: Options<FilesControllerGetFileData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: "/api/files/{fileId}",
    ...options,
  });
};
