// This file is auto-generated by @hey-api/openapi-ts
import { z } from "zod";

export const zCompanyCreateDto = z.object({
  name: z.string(),
  city: z.string().optional(),
  region: z.string(),
  inn: z.number(),
  brands: z.array(z.string()).optional(),
});

export const zIncomeDto = z.object({
  amount: z.number(),
  currency: z.string(),
});

export const zFullNameDto = z.object({
  firstName: z.string(),
  lastName: z.string(),
  middleName: z.string().optional(),
});

export const zJobseekerProfileDto = z.object({
  photo: z.string().optional(),
  video: z.string().optional(),
  position: z.string(),
  income: zIncomeDto,
  fullName: zFullNameDto,
  phone: z.string(),
  gender: z.enum(["Male", "Female"]),
  birthday: z.string().datetime(),
  region: z.string(),
});

export const zWorkExperienceDto = z.object({
  company: z.string(),
  position: z.string(),
  startDate: z.string().datetime(),
  endDate: z.string().datetime(),
  responsibilitiesDescription: z.string(),
  employmentType: z.enum(["FullTime", "PartTime", "Remote", "Office", "Hybrid"]),
});

export const zEducationDto = z.object({
  university: z.string(),
  faculty: z.string(),
  degree: z.string(),
  graduationDate: z.string().datetime(),
});

export const zSkillDto = z.object({
  name: z.string(),
  level: z.enum(["Beginner", "Intermediate", "Advanced"]),
});

export const zResumeCreateDto = z.object({
  jobseekerId: z.string(),
  position: z.string(),
  income: zIncomeDto,
  fullName: zFullNameDto,
  gender: z.enum(["Male", "Female"]),
  birthday: z.string().datetime(),
  email: z.string(),
  phone: z.string(),
  city: z.string(),
  workExperience: z.array(zWorkExperienceDto),
  education: z.array(zEducationDto).optional(),
  skills: z.array(zSkillDto).optional(),
});

export const zJobseekerCreateDto = z.object({
  profile: zJobseekerProfileDto,
  resumes: z.array(zResumeCreateDto).optional(),
});

export const zRegisterDto = z.object({
  email: z.string(),
  phone: z.string(),
  password: z.string().min(8).max(20),
  role: z.enum(["Company", "Jobseeker", "Admin"]),
  firstName: z.string(),
  lastName: z.string(),
  displayName: z.string(),
  company: zCompanyCreateDto.optional(),
  jobseeker: zJobseekerCreateDto.optional(),
});

export const zResponse = z.object({});

export const zLoginDto = z.object({
  email: z.string(),
  password: z.string().min(8).max(20),
});

export const zLoginByPhoneDto = z.object({
  phone: z.string(),
  password: z.string(),
});

export const zRegistrationStep1Dto = z.object({
  email: z.string(),
  role: z.enum(["Company", "Jobseeker", "Admin"]),
  password: z.string(),
});

export const zRegistrationStartResponseDto = z.object({
  sessionId: z.string(),
  currentStep: z.number(),
});

export const zRegistrationStep2Dto = z.object({
  sessionId: z.string(),
  firstName: z.string(),
  lastName: z.string(),
});

export const zRegistrationStep3Dto = z.object({
  sessionId: z.string(),
  phone: z.string(),
});

export const zRegistrationSendSmsDto = z.object({
  sessionId: z.string(),
});

export const zRegistrationVerifySmsDto = z.object({
  sessionId: z.string(),
  code: z.string(),
});

export const zCompanyDto = z.object({
  name: z.string(),
  phone: z.string(),
  city: z.string().optional(),
  region: z.string(),
  inn: z.number(),
  brands: z.array(z.string()).optional(),
});

export const zJobseekerDto = z.object({});

export const zRegistrationStep5Dto = z.object({
  sessionId: z.string(),
  company: zCompanyDto.optional(),
  jobseeker: zJobseekerDto.optional(),
});

export const zRegistrationCompleteDto = z.object({
  sessionId: z.string(),
});

export const zVacancyResponseDto = z.object({
  _id: z.string(),
  title: z.string(),
  description: z.string(),
  employmentType: z.enum(["FullTime", "PartTime", "Remote", "Office", "Hybrid"]),
  experience: z.enum(["Intern", "Junior", "Middle", "Senior", "Manager", "Director"]),
  salary: z.object({}),
  companyId: z.string(),
  brands: z.array(z.string()),
  city: z.string(),
  employmentTypes: z.enum(["FullTime", "PartTime", "Remote", "Office", "Hybrid"]),
});

export const zSalaryDto = z.object({
  amount: z.object({}),
  currency: z.string(),
});

export const zVacancyCreateDto = z.object({
  title: z.string(),
  description: z.string(),
  salary: zSalaryDto,
  city: z.string(),
  experience: z.enum(["Intern", "Junior", "Middle", "Senior", "Manager", "Director"]),
  employmentTypes: z.array(z.enum(["FullTime", "PartTime", "Remote", "Office", "Hybrid"])),
  brands: z.array(z.array(z.unknown())),
});

export const zVacancyUpdateDto = z.object({
  title: z.string(),
  description: z.string(),
  salary: zSalaryDto,
  city: z.string(),
  experience: z.enum(["Intern", "Junior", "Middle", "Senior", "Manager", "Director"]),
  employmentTypes: z.array(z.enum(["FullTime", "PartTime", "Remote", "Office", "Hybrid"])),
});

export const zVacancyDeleteDto = z.object({
  companyId: z.string(),
});

export const zUpdateCompanyDto = z.object({
  name: z.string().optional(),
  city: z.string().optional(),
});

export const zUpdateCompanyResponseDto = z.object({
  success: z.boolean(),
  company: zUpdateCompanyDto,
});

export const zUpdateIncomeDto = z.object({
  amount: z.number().optional(),
  currency: z.string().optional(),
});

export const zUpdateFullNameDto = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  middleName: z.string().optional(),
});

export const zUpdateJobseekerProfileDto = z.object({
  photo: z.string().optional(),
  video: z.string().optional(),
  position: z.string().optional(),
  income: zUpdateIncomeDto.optional(),
  fullName: zUpdateFullNameDto.optional(),
  phone: z.string().optional(),
  gender: z.enum(["Male", "Female"]).optional(),
  birthday: z.string().datetime().optional(),
  region: z.string().optional(),
});

export const zUpdateJobseekerDto = z.object({
  userId: z.string().optional(),
  profile: zUpdateJobseekerProfileDto.optional(),
  resumes: z.array(z.string()).optional(),
});

export const zUpdateJobseekerResponseDto = z.object({
  success: z.boolean().optional(),
  jobseeker: z.object({}).optional(),
});

export const zResumeUpdateDto = z.object({
  position: z.string().optional(),
  income: zIncomeDto.optional(),
  fullName: zFullNameDto.optional(),
  gender: z.enum(["Male", "Female"]).optional(),
  birthday: z.string().datetime().optional(),
  email: z.string().optional(),
  phone: z.string().optional(),
  city: z.string().optional(),
  workExperience: z.array(zWorkExperienceDto).optional(),
  education: z.array(zEducationDto).optional(),
  skills: z.array(zSkillDto).optional(),
});

export const zCreateSubscriptionRequestDto = z.object({
  companyId: z.string(),
  subscriptionId: z.string(),
});

export const zCreateSubscriptionResponseDto = z.object({
  paymentUrl: z.string(),
});

export const zSubscriptionPriceDto = z.object({
  monthly: z.number(),
  annual: z.number(),
});

export const zCreateSubscriptionDto = z.object({
  plan: z.string(),
  duration: z.number(),
  price: zSubscriptionPriceDto,
});

export const zSubscriptionResponseDto = z.object({
  _id: z.string(),
  plan: z.string(),
  duration: z.number(),
  price: zSubscriptionPriceDto,
  startDate: z.string().datetime().optional(),
  endDate: z.string().datetime().optional(),
  status: z.enum(["STARTED", "WAITING_FOR_PAYMENT", "ACTIVE", "EXPIRED", "CANCELED"]),
});

export const zUpdateSubscriptionDto = z.object({
  plan: z.string().optional(),
  duration: z.number().optional(),
  price: zSubscriptionPriceDto.optional(),
  startDate: z.string().datetime().optional(),
  endDate: z.string().datetime().optional(),
  status: z.enum(["STARTED", "WAITING_FOR_PAYMENT", "ACTIVE", "EXPIRED", "CANCELED"]).optional(),
});

export const zAuthControllerRegisterResponse = zResponse;

export const zAuthControllerLoginResponse = zResponse;

export const zAuthControllerLoginByPhoneResponse = z.object({
  access_token: z.string().optional(),
  refresh_token: z.string().optional(),
});

export const zAuthControllerRefreshTokensResponse = z.object({
  access_token: z.string().optional(),
  refresh_token: z.string().optional(),
});

export const zRegistrationControllerStartRegistrationResponse = zRegistrationStartResponseDto;

export const zRegistrationControllerCompleteRegistrationResponse = z.object({
  access_token: z.string().optional(),
  refresh_token: z.string().optional(),
});

export const zRegistrationControllerGetRegistrationStatusResponse = z.object({
  sessionId: z.string().optional(),
  currentStep: z.number().optional(),
});

export const zUserControllerMeResponse = z.object({
  user: z.unknown().optional(),
  company: z.unknown().optional(),
  jobseeker: z.unknown().optional(),
});

export const zUserControllerListResponse = z.object({
  users: z.array(zRegisterDto).optional(),
});

export const zVacancyControllerListResponse = z.array(zVacancyResponseDto);

export const zVacancyControllerCreateResponse = zVacancyResponseDto;

export const zVacancyControllerUpdateResponse = zVacancyResponseDto;

export const zVacancyControllerDeleteMultipleResponse = z.object({
  message: z.string().optional(),
  deletedCount: z.number().optional(),
});

export const zVacancyControllerGetByCompanyIdResponse = z.array(zVacancyResponseDto);

export const zVacancyControllerCreateByCompanyIdResponse = zVacancyResponseDto;

export const zVacancyControllerUpdateByCompanyIdResponse = zVacancyResponseDto;

export const zCompanyControllerListResponse = z.object({
  _id: z.string().optional(),
  name: z.string().optional(),
  city: z.string().optional(),
  userId: z.string().optional(),
  vacancies: z.array(zVacancyCreateDto).optional(),
});

export const zCompanyControllerGetByIdResponse = z.object({
  _id: z.string().optional(),
  name: z.string().optional(),
  region: z.string().optional(),
  city: z.string().optional(),
  phone: z.string().optional(),
  inn: z.number().optional(),
  userId: z.string().optional(),
  brands: z.array(z.string()).optional(),
  logoUrl: z.string().optional(),
  certificateUrls: z.array(z.string()).optional(),
  documentUrls: z.array(z.string()).optional(),
  vacancies: z.array(zVacancyCreateDto).optional(),
});

export const zCompanyControllerUpdateResponse = zUpdateCompanyResponseDto;

export const zCompanyControllerDeleteResponse = z.object({
  message: z.string().optional(),
});

export const zJobseekerControllerGetByIdResponse = z.object({
  _id: z.string().optional(),
  profile: z
    .object({
      photo: z.string().optional(),
      video: z.string().optional(),
      position: z.string().optional(),
      income: z
        .object({
          amount: z.number().optional(),
          currency: z.string().optional(),
        })
        .optional(),
      fullName: z
        .object({
          firstName: z.string().optional(),
          lastName: z.string().optional(),
          middleName: z.string().optional(),
        })
        .optional(),
      phone: z.string().optional(),
      gender: z.string().optional(),
      birthday: z.string().date().optional(),
      region: z.string().optional(),
    })
    .optional(),
  userId: z.string().optional(),
  resumes: z
    .array(
      z.object({
        _id: z.string().optional(),
        position: z.string().optional(),
      }),
    )
    .optional(),
  documentFileIds: z.array(z.string()).optional(),
  certificateFileIds: z.array(z.string()).optional(),
});

export const zJobseekerControllerListResponse = z.object({
  jobseekers: z
    .array(
      z.object({
        _id: z.string().optional(),
        firstName: z.string().optional(),
        lastName: z.string().optional(),
        email: z.string().optional(),
        userId: z.string().optional(),
        resumes: z.array(zResumeCreateDto).optional(),
      }),
    )
    .optional(),
});

export const zJobseekerControllerUpdateResponse = zUpdateJobseekerResponseDto;

export const zJobseekerControllerDeleteResponse = z.object({
  message: z.string().optional(),
});

export const zJobseekerControllerUploadPhotoResponse = z.object({
  success: z.boolean().optional(),
  fileId: z.string().optional(),
  message: z.string().optional(),
});

export const zJobseekerControllerUploadVideoResponse = z.object({
  success: z.boolean().optional(),
  fileId: z.string().optional(),
  message: z.string().optional(),
});

export const zResumeControllerListResponse = z.array(zResumeCreateDto);

export const zResumeControllerCreateResponse = zResumeCreateDto;

export const zResumeControllerUpdateResponse = zResumeUpdateDto;

export const zResumeControllerDeleteResponse = z.object({
  message: z.string().optional(),
});

export const zSubscriptionControllerCreateResponse = zCreateSubscriptionResponseDto;

export const zSubscriptionAdminControllerCreateCompanySubscriptionResponse =
  zSubscriptionResponseDto;

export const zSubscriptionAdminControllerGetAllSubscriptionsResponse =
  z.array(zSubscriptionResponseDto);

export const zSubscriptionAdminControllerDeleteSubscriptionResponse = z.object({
  success: z.boolean().optional(),
  message: z.string().optional(),
});

export const zSubscriptionAdminControllerGetSubscriptionByIdResponse = zSubscriptionResponseDto;

export const zSubscriptionAdminControllerUpdateSubscriptionResponse = zSubscriptionResponseDto;
